### ISSUE TITLE
Script fails when no instance is provided during scan

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/geodata-processing#15]
for example: 

(arcgispro-py3) R:\ARCHIVE_PROJECT\GeoData_Ingest\archives\gbl\ingested_20191105>update2 -s .
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3
**Instance argument is null. Defaulting to dev...**
Performing QA scan...
Checking for duplicate UUIDs...
Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by Wiscmapper** [comment]
As part of this @eliaswilz, I'm not sure if you merged your latest branch into Master? I'm not 100% clear if Jaime is using the latest version of your script.

**Comment by Wiscmapper** [comment]
as of 11/26, on hold until @eliaswilz finishes up some other work.
